// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// shingle_ngrams
CharacterVector shingle_ngrams(CharacterVector words, int n);
RcppExport SEXP tokenizers_shingle_ngrams(SEXP wordsSEXP, SEXP nSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< CharacterVector >::type words(wordsSEXP);
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    __result = Rcpp::wrap(shingle_ngrams(words, n));
    return __result;
END_RCPP
}
// generate_ngrams
CharacterVector generate_ngrams(const CharacterVector terms, const uint32_t ngram_min, const uint32_t ngram_max, const CharacterVector stopwords, const String ngram_delim);
RcppExport SEXP tokenizers_generate_ngrams(SEXP termsSEXP, SEXP ngram_minSEXP, SEXP ngram_maxSEXP, SEXP stopwordsSEXP, SEXP ngram_delimSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< const CharacterVector >::type terms(termsSEXP);
    Rcpp::traits::input_parameter< const uint32_t >::type ngram_min(ngram_minSEXP);
    Rcpp::traits::input_parameter< const uint32_t >::type ngram_max(ngram_maxSEXP);
    Rcpp::traits::input_parameter< const CharacterVector >::type stopwords(stopwordsSEXP);
    Rcpp::traits::input_parameter< const String >::type ngram_delim(ngram_delimSEXP);
    __result = Rcpp::wrap(generate_ngrams(terms, ngram_min, ngram_max, stopwords, ngram_delim));
    return __result;
END_RCPP
}
// generate_ngrams_batch
ListOf<CharacterVector> generate_ngrams_batch(const ListOf<const CharacterVector> documents_list, const uint32_t ngram_min, const uint32_t ngram_max, const CharacterVector stopwords, const String ngram_delim);
RcppExport SEXP tokenizers_generate_ngrams_batch(SEXP documents_listSEXP, SEXP ngram_minSEXP, SEXP ngram_maxSEXP, SEXP stopwordsSEXP, SEXP ngram_delimSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< const ListOf<const CharacterVector> >::type documents_list(documents_listSEXP);
    Rcpp::traits::input_parameter< const uint32_t >::type ngram_min(ngram_minSEXP);
    Rcpp::traits::input_parameter< const uint32_t >::type ngram_max(ngram_maxSEXP);
    Rcpp::traits::input_parameter< const CharacterVector >::type stopwords(stopwordsSEXP);
    Rcpp::traits::input_parameter< const String >::type ngram_delim(ngram_delimSEXP);
    __result = Rcpp::wrap(generate_ngrams_batch(documents_list, ngram_min, ngram_max, stopwords, ngram_delim));
    return __result;
END_RCPP
}
// skip_ngrams
CharacterVector skip_ngrams(CharacterVector words, int n, int k);
RcppExport SEXP tokenizers_skip_ngrams(SEXP wordsSEXP, SEXP nSEXP, SEXP kSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< CharacterVector >::type words(wordsSEXP);
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< int >::type k(kSEXP);
    __result = Rcpp::wrap(skip_ngrams(words, n, k));
    return __result;
END_RCPP
}
