# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

shingle_ngrams <- function(words, n) {
    .Call('tokenizers_shingle_ngrams', PACKAGE = 'tokenizers', words, n)
}

skip_ngrams <- function(words, n, k) {
    .Call('tokenizers_skip_ngrams', PACKAGE = 'tokenizers', words, n, k)
}

